name: 'Hello World'
description: Greeting
runs:
  using: "composite"
  steps:
    - run: echo Hello there once!
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::error::Testing error"
    - run: echo Hello there again number 2!
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::error::Testing error"
